### ISSUE TITLE
Execute in .Net Core?

### ISSUE THREAD

**Issue by MathiasMagnus** [node4good/get-vs2017-path#1]
Hi!
I'm trying to distill from your scripts something I can use in my environment. The example .cmd invokes the system PowerShell which works fine, but when I try to Add-Type in a PS Core instance, I get errors.
```PowerShell
Add-Type : (166) : 'TypeLibImportClassAttribute' is inaccessible due to its protection level
At line:1 char:1
+ Add-Type -Path .\Get-VS7.cs;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Microsoft.Power...peCompilerError:AddTypeCompilerError) [Add-Type], Except
   ion
    + FullyQualifiedErrorId : SOURCE_CODE_ERROR,Microsoft.PowerShell.Commands.AddTypeCommand
```
I could not even find this type in PS/.Net Core (I find the new docs.microsoft page very hard to use). Could you help me out with a workaround? I am a total C# noob.

**Comment by refack** [comment]
I'm a .Net core noob, but I'll have a look around...

**Comment by refack** [comment]
@MathiasMagnus could you try now?
Also how do you run Powershell on .NET Core?

**Comment by MathiasMagnus** [comment]
You can grab an .msi or .zip from the [Releases](https://github.com/PowerShell/PowerShell/releases) section. It happily lives side-by-side the stock version. The nightlies also have .appx installers.

**Comment by refack** [comment]
I was able to run it now with a PS "Core", @MathiasMagnus could you give it a try?

**Comment by MathiasMagnus** [comment]
Works like a charm. Thanks. All I needed was to obtain the install location as a string. Modified the source to have:
```C#
public static String Query()
        {
                        ISetupConfiguration query = new SetupConfiguration();
                        ISetupConfiguration2 query2 = (ISetupConfiguration2) query;
                        IEnumSetupInstances e = query2.EnumAllInstances();
                        ISetupInstance2[] rgelt = new ISetupInstance2[1];
                        int pceltFetched;
                        do
                        {
                                e.Next(1, rgelt, out pceltFetched);
                                if (pceltFetched > 0)
                                        return rgelt[0].GetInstallationPath();
                        } while (pceltFetched > 0);
                        return "";
        }

```
And I invoke it as such:
```Powershell
Add-Type -Path .\Get-VS7.cs;
$location = [VisualStudioConfiguration.Main]::Query();
```
Is this absolutely barbaric? It might return an array of strings, but for the moment I'm content with being able to enumerate the only install I have on my machine.

**Comment by refack** [comment]
I say, if it works, it's the right thing!
If you know you won't install multiple versions, then you're set.
