### ISSUE TITLE
Methods to find VS

### ISSUE THREAD

**Issue by joaocgreis** [node4good/get-vs2017-path#3]
The registry method is broken, it does not find the SDK. I see no good way to fix it, and the registry variable itself is unreliable. I think it should be removed.

Is there any case where the Powershell method (first one) fails and others succeed?

So, shouldn't there be only one method (Powershell)?

**Comment by refack** [comment]
I have yet to find a reproducible scenario that fails for the first one. But....
Failing builds is one of the most frustrating and FAQed issues out there, so I feel that having a backup is good.

**Comment by refack** [comment]
So.... I fixed `try_registry` ;)
